### PR TITLE
Added Chromium 10.0.601.0 to supported browsers

### PR DESCRIPTION
**Pull request by rabidaudio**
I was hoping to add an early version of chrome, per #11 . The earliest pre-built binary I could find on [chromium-browser-snapshots](https://commondatastorage.googleapis.com/chromium-browser-snapshots) was `10.0.601.0`, circa ~2011. However, this could be used as a base for including other versions of chrome/chromium (just specify the proper binary).

I didn't actually publish the image, wanted someone else's eyes on it first (this is basically my first time playing with docker).

### CODE REVIEW

**Comment by ikreymer** [comment]
Thanks for this. The image builds pretty well and runs, although it looks like all the text is missing, at least for me? Perhaps some fonts need to be installed? or maybe an issue with this release?
I will search as well when I get a chance..

screen shot 2015-12-06 at 4 43 53 pm

**Comment by rabidaudio** [comment]
Hmm. I missed this because I'm actually experiencing an issue with the site where I can't actually click inside with the VNC area of the site (Google Chrome 45.0.2454.101 on Arch x64). Works fine in Firefox. I can open an issue for this if you like.

Missing dep might be `libfreetype6` since it is on the list of deps for [chromium 6 on Debian](https://packages.debian.org/squeeze/chromium-browser). I'll try this shortly.

Also, in hindsight, `72316` might be a better position to use than `68155`, since it's `10.0.648` which is an [actual major release](https://en.wikipedia.org/wiki/Google_Chrome_release_history). There's also `44202` which is version `5.0.375` which is actually the oldest stable release on the system (circa 2010). Not sure why I didn't find it before.

**Comment by ikreymer** [comment]
> Hmm. I missed this because I'm actually experiencing an issue with the site where I can't actually click inside with the VNC area of the site (Google Chrome 45.0.2454.101 on Arch x64). Works fine in Firefox. I can open an issue for this if you like.

I have not heard of this issue before.. clicking has worked on several platforms that I've tested, even android.. I wonder if its a noVNC issue? Only other thing I can think of is focus somehow not be passed to the VNC client..

Yeah, let me know which versions make sense, probably earlier the better..

**Comment by rabidaudio** [comment]
It turns out the font issue wasn't occurring for me after all, not sure why they aren't there for you. Anyway I added a few more dependencies just to be sure.

Also bumped `chromium10` to `10.0.648` and added `chromium5` to `5.0.375`. Feel free to use either or both.

screenshot from 2015-12-06 22-34-02

screenshot from 2015-12-06 22-48-50

**Comment by rabidaudio** [comment]
Also it seems the mouse issue is noVNC related (Chrome+touchscreen seems to cause it to only respond to touch events instead of mouse events): https://github.com/kanaka/noVNC/pull/369

**Comment by ikreymer** [comment]
Ah ok, good to know about the noVNC issue. I refactored common init into a base-chromium container, latest branch: https://github.com/ikreymer/netcapsule/tree/chromium

**Comment by ikreymer** [comment]
@rabidaudio Chromium 5 is live now (and 10 too, though didn't add a menu entry for it) Thanks for the contribution!

**Comment by rabidaudio** [comment]
:tada: awesome!

**Pull request merged**
